core/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.templates_app.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/templates_app/models.py
from django.db import models

# from core.helpers import phone_regex


class Order(models.Model):
    class Meta:
        verbose_name = '1. Заказ'
        verbose_name_plural = '1. Заказы'

    MATERIAL_CHOICES = (
        ('Кожа', 'Кожа'),
        ('Пластик', 'Пластик'),
        ('Ткань', 'Ткань'),
        ('Холст', 'Холст'),
        ('Кирпич', 'Кирпич'),
        ('Обои', 'Обои'),
        ('Стекло', 'Стекло'),
        ('Дерево', 'Дерево'),
        ('Металл', 'Металл'),
        ('Паркет', 'Паркет'),
        ('Ламинат', 'Ламинат'),
        ('Штукатурка', 'Штукатурка'),
    )

    material = models.CharField(
        verbose_name='Материал',
        max_length=25,
        choices=MATERIAL_CHOICES,
        null=True,
    )

    first_name = models.CharField(
        max_length=255,
        verbose_name='Имя',
    )
    phone_number = models.CharField(
        max_length=19,
        verbose_name='Телефон',
        # validators=[phone_regex]
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name='Дата отправки',
        null=True,
    )
    is_read = models.BooleanField(
        default=False,
        verbose_name='Прочитано?',
    )

    height = models.IntegerField(
        verbose_name='Высота',
        null=True,
        blank=True
    )

    width = models.IntegerField(
        verbose_name='Ширина',
        null=True,
        blank=True
    )

    price = models.IntegerField(
        verbose_name='Цена',
        null=True,
        blank=True
    )
    image = models.FileField(
        null=True, blank=True,
        upload_to='feedback_images',
        verbose_name='Картинка'
    )

    def __str__(self):
        return self.first_name


class IndividualOrder(models.Model):
    class Meta:
        verbose_name = '2. Индивидуальный Заказ'
        verbose_name_plural = '2. Индивидуальные Заказы'

    first_name = models.CharField(
        max_length=255,
        verbose_name='Имя',
    )
    phone_number = models.CharField(
        max_length=19,
        verbose_name='Телефон',
        # validators=[phone_regex]
    )
    comment = models.TextField(
        verbose_name='Комментарий',
    )
    created_at = models.DateField(
        auto_now_add=True,
        verbose_name='Дата отправки',
        null=True,
    )
    is_read = models.BooleanField(
        default=False,
        verbose_name='Прочитано?',
    )

    def __str__(self):
        return self.first_name


class Gallery(models.Model):
    image = models.FileField(
        null=False,
        blank=False,
        upload_to='gallery',
        verbose_name='Галерея'
    )

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Галерея'


class Counter(models.Model):
    count = models.IntegerField(
        verbose_name='Просмотры',
        default=0
    )

    class Meta:
        verbose_name = 'Просмотр'
        verbose_name_plural = 'Просмотры'

    def __str__(self):
        return self.count


class TelegramChatBot(models.Model):
    class Meta:
        verbose_name = 'Telegram Бот'
        verbose_name_plural = 'Telegram Бот'

    token = models.CharField(
        verbose_name='Telegram Бот Токен',
        max_length=255,
    )
    group_id = models.CharField(
        verbose_name='Group ID',
        max_length=255,
    )

    def __str__(self):
        return f'Telegram чат : {self.token}'

templates/pages/gallery.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}
{% block page %}another-background gallery-page{% endblock %}
{% block style-libs %}
        <link rel="stylesheet" href="{% static 'light-gallery/gallery/css/lightgallery.min.css' %}">
{% endblock %}

{% block content %}
    <section class="gallery-section">
        <div class="container">
        {% if request.user.is_authenticated %}
        <form action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}
        <label for="id_image">
                    <input class="input" type="file" name="image" id="id_image" hidden>
            <span class="input-file button">Прикрепить</span>
        </label>
            <button class="button" type="submit">Добавить</button>
        </form>
        {% endif %}
            <div class="gallery__content" id="lightgallery">
{#                <a href="{% static 'img/jpg/add-circle-1_48180.png' %}">#}
{#                    <img src="{% static 'img/jpg/add-circle-1_48180.png' %}" alt="" style="background: whitesmoke">#}
{#                </a>#}
                {% for image in images %}
                    <a href="{{ image.image.url }}">
                    <img src="{{ image.image.url }}" alt="" style="width: 224px; height: 224px">
                    </a>
                {% endfor %}
{#                <a href="{% static 'img/jpg/img1.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img1.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img2.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img2.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img3.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img3.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img1.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img1.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img2.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img2.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img3.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img3.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img1.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img1.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img2.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img2.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img3.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img3.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img1.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img1.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img2.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img2.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img3.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img3.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img1.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img1.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img2.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img2.jpg' %}" alt="">#}
{#                </a>#}
{#                <a href="{% static 'img/jpg/img3.jpg' %}">#}
{#                    <img src="{% static 'img/jpg/img3.jpg' %}" alt="">#}
{#                </a>#}
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    <script src="{% static 'light-gallery/gallery/js/lightgallery-all.min.js' %}"></script>
    <script src="{%  static 'js/login_modal.js' %}"></script>
{#    LOGIN BUTTON#}
    {% if not request.user.is_authenticated %}
    <script>
        $('.header__list-link').append('<li class="header__link login" ' +
            'style="color:black">Войти</li>');
        $('.login').click(function () {
            $('.modal_login').addClass('show');
            console.log('SHOW!')
        })
    </script>
    {% endif %}
{#    END LOGIN BUTTON#}
    <script>
        $(document).ready(function () {
            $('#lightgallery').lightGallery();
        });
        $('#our_service').click(function () {
            window.location.replace(window.location.origin + '#our-service')
            });
        $('#our_directions').click(function () {
            window.location.replace(window.location.origin + '#our-directions')
            });
    </script>
{% endblock %}

templates/pages/individual_order.html
{% extends 'base.html' %}
{% load static %}

{% block title_page %}{% endblock %}
{% block page %}another-background{% endblock %}

{% block content %}
    <section class="individual-order">
        <div class="container">
            <div class="individual-order__content">
                <div class="left">
                    <div class="left-image">
                        <img src="{% static 'img/jpg/individual-left.jpg' %}"
                             alt="load img">
                        <div class="description">
                            Мы выполним за Вас работу под ключ. Если не знаете,
                            что нанести на поверхность, не знаете как
                            разнообразить свое пространство, то Вы можете нам
                            написать и наш дизайнер разработает для Вас
                            персональный эскиз
                        </div>
                    </div>
                </div>
                <div class="right">
                    <div class="form-section__content">
                        <form action="" method="post">
                        {% csrf_token %}
                            <h2 class="section-title">
                                Если у Вас остались вопросы
                            </h2>
                            <p class="description">Оставьте заявку и мы
                                обязательно Вам перезвоним</p>
                            <label class="input-text">
                                {{ individual_order_form.first_name  }}
                                {% if order_form.first_name.errors %}
                                    <span class="error">
                                        {{ order_form.first_name.errors }}
                                    </span>
                                {% endif %}
{#                                <input class="input" type="text"#}
{#                                       placeholder="Как к Вам обращаться?">#}
{#                                <span class="error">ошибка</span>#}
                            </label>
                            <label class="input-text">
                                {{ individual_order_form.phone_number }}
                             {% if individual_order_form.phone_number.errors %}
                                <span class="error">
                                 {{ individual_order_form.phone_number.errors }}
                                </span>
                             {% endif %}
{#                                <input class="input phone_mask" type="text"#}
{#                                       placeholder="Номер телефона">#}
                            </label>
                            <label class="input-text">
                                {{ individual_order_form.comment }}
{#                                <textarea class="input textarea" type="text"#}
{#                                              placeholder="Комментарий"></textarea>#}
                            </label>
                            <button class="button" type="submit">Отправить
                            </button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

{% block scripts %}
    {% if success %}
    <script>
        $('#modal_success').addClass('show')
    </script>
    {% endif %}
    <script>
$('#our_service').click(function () {
    window.location.replace(window.location.origin + '#our-service')
    });
$('#our_directions').click(function () {
    window.location.replace(window.location.origin + '#our-directions')
    });
    </script>
{% endblock %}